Repository Git-kkalnane/starbucks-backend, pull requests merged in 2025-06, with the labels that each got.

#50 Feat : inquiry, store entity 추가
  starbucks/src/main/java/git_kkalnane/backend/starbucks/global/entity/BaseTimeEntity.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/common/success/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/controller/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/domain/Inquiry.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/domain/InquiryCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/domain/InquiryStatus.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/dto/request/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/dto/response/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/common/success/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/controller/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/domain/CrowdLevel.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/domain/Store.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/dto/request/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/dto/response/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/service/.gitkeep
Labels: feature

#52 feat : 인증관련 초기 기능 구성
  .idea/dataSources.xml
  .idea/gradle.xml
  starbucks/build.gradle
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/exception/AuthErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/exception/AuthException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtToken.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtTokenProvider.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/jwt/config/JwtTokenConfig.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/success/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/success/AuthSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/controller/AuthController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/domain/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/domain/AuthInfo.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/repository/AuthInfoRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/service/AuthService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/global/config/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/global/config/AuthInterceptor.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/global/config/WebConfig.java
Labels: feature

#82 [feat] 매장 상세 조회 API 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/error/handler/GlobalErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/error/handler/GlobalExceptionHandler.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/domain/Inquiry.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/common/exception/StoreErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/common/exception/StoreException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/common/success/StoreSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/controller/StoreController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/controller/매장상세조회API.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/domain/CrowdLevel.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/domain/Store.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/dto/response/StoreDetailsResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/repository/StoreRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/service/StoreService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/store/service/StoreServiceTest.java
Labels: feature

#99 [refactor] 상품 전체 조회 API 분리
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/ItemController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/item-api-test.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/service/ItemService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/item/service/ItemServiceTest.java
Labels: refactor

#100 [feat] 알림 전송 및 구독 기능 개발
  starbucks/.gitignore
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/common/exception/NotificationErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/common/exception/NotificationException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/common/success/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/common/success/NotificationSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/NotificationController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/Notification.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/NotificationTargetType.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/NotificationType.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/SseEmitterId.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/vo/NotificationEvent.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/vo/NotificationReceiver.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/vo/NotificationSender.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/request/NotificationSendRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/NotificationResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/repository/EmitterRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/repository/EmitterRepositoryImpl.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/repository/NotificationRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/service/NotificationService.java
Labels: feature

#101 [test] 알림 전송 및 구독 기능 테스트
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/NotificationController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/notification.http
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/NotificationServiceTest.java
Labels: test

#107 [test] 알림 전송 및 구독 기능 테스트
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/NotificationController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/notification.http
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/NotificationServiceTest.java
Labels: test

#95 [feat] 상품 목록 조회 기능 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/common/success/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/controller/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/dto/request/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/dto/response/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/inquiry/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/common/success/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/common/success/ItemSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/ItemController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/item-api-test.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/ItemOption.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/ItemType.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/enums/BeverageSizeOption.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/dessert/DessertItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/dto/response/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/dto/response/ItemListResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/dto/response/ItemSummaryResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/repository/BeverageItemRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/repository/DessertItemRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/service/ItemService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/item/service/ItemServiceTest.java
Labels: feature

#103 [feat] 지점 목록 조회 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/common/success/StoreSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/controller/StoreController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/controller/매장상세조회API.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/controller/매장조회API.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/dto/response/StoreListResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/dto/response/StoreSummaryResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/service/StoreService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/store/service/StoreServiceTest.java
Labels: feature

#121 [feat] 주문 내용 저장 기능 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/domain/Order.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/request/OrderItemRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderCreateTest.java
Labels: feature

#126 [feat] 주문 상세 조회 기능 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/exception/OrderErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/success/OrderSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/주문상세조회API.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/OrderDetailResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/OrderItemDetailResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: feature

#114 [test] 알림 목록 조회 테스트
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/notification.http
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/NotificationServiceTest.java
Labels: test

#117 [feat] 로그인 로직 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/exception/AuthErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtToken.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtTokenProvider.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/jwt/config/JwtTokenConfig.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/success/AuthSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/controller/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/controller/AuthController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/domain/AccessToken.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/domain/AuthInfo.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/domain/RefreshToken.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/LoginDto.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/UserInfo.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/request/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/request/LoginRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/response/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/response/LoginResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/repository/AccessTokenRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/repository/AuthInfoRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/repository/RefreshTokenRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/service/AuthService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/utils/CookieGenerator.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/repository/MemberRepository.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtTokenProviderTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/service/AuthServiceTest.java
Labels: feature

#138 [Refactor] ItemType변경에 의한 에러해결
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/dto/response/ItemSummaryResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/OrderItemDetailResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/item/service/ItemServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderCreateTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: refactor

#141 [refactor] 과거 주문 내용 목록 조회 기능 수정
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/OrderListResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/OrderSummaryResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/repository/OrderRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: refactor

#142 [fix] 테스트 코드 에러 수정
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtTokenProviderTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/service/AuthServiceTest.java
Labels: fix

#149 [fix] 테스트 코드 오류 수정
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtTokenProviderTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/service/AuthServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/service/MemberServiceTest.java
Labels: fix

#143 [Feat] 카트아이템 삭제 로직 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/success/CartSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/CartController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/카트 아이템 삭제.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/repository/CartRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/service/CartService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/ItemCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/enums/BeverageSizeOption.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/dessert/DessertCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/domain/Order.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PayCard.java
Labels: feature

#124 [Feat] 장바구니 수정 로직 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/exception/CartErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/success/CartSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/CartController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/카트 아이템 삭제.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/카트수정.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/domain/CartItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/AddCartItemOptionRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/AddCartItemRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/AddItemsRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/ModifyCartItemRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/ModifyCartItemsRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/AddCartItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/AddCartItemsResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/CartAddItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/ModifyCartItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/ModifyCartItemsResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/repository/CartRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/service/CartService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/common/exception/ItemErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/ItemCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/enums/BeverageSizeOption.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/dessert/DessertCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/domain/Order.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PayCard.java
Labels: feature

#118 [Feat] 장바구니 메뉴 추가 API 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/exception/CartErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/exception/CartException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/success/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/success/CartSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/CartController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/카트 아이템 삭제.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/카트메뉴담기.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/카트수정.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/domain/Cart.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/domain/CartItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/AddCartItemOptionRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/AddCartItemRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/AddItemsRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/ModifyCartItemRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/request/ModifyCartItemsRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/AddCartItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/AddCartItemsResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/ModifyCartItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/dto/response/ModifyCartItemsResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/repository/CartItemRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/repository/CartRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/service/CartService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/common/exception/ItemErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/common/exception/ItemException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/ItemCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/ItemOption.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/CartItemOption.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/dessert/DessertCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/repository/DessertItemRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PayCard.java
Labels: feature

#154 fix: 오타 수정
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/domain/CartItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/service/CartService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
Labels: refactor, fix

#153 [refactor] OrderService 수정
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
Labels: refactor

#155 [feat] 현재 준비중인 주문 내용 조회 기능 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/exception/OrderErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/success/OrderSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/주문API.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/domain/Order.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/domain/OrderItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/CurrentOrderResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/repository/OrderRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: feature

#171 [refactor] 매장 목록 조회 시 드라이브 쓰루 여부 표시
  starbucks/src/main/java/git_kkalnane/backend/starbucks/store/dto/response/StoreSummaryResponse.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/store/service/StoreServiceTest.java
Labels: refactor

#172 [test] 로그아웃 테스트 코드 작성
  starbucks/.gitignore
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/service/AuthServiceTest.java
Labels: test

#173 [Refactor] 엔티티 수정
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/beverage/BeverageItemCategory.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/dessert/DessertItem.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/domain/dessert/DessertItemCategory.java
Labels: refactor

#177 [fix] Order 엔티티 에러 수정
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/domain/Order.java
Labels: fix

#181 [test] 액세스 토큰 검증 로직 테스트 코드 구현
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/service/AuthServiceTest.java
Labels: test

#157 [test] : 결제 기능 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/common/exception/PayCardErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PayCard.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PointRewardRatio.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderCreateTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/domain/PayCardTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/domain/PointRewardRatioTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/service/PayCardServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/service/PointTransactionServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/payment/service/PaymentServiceTest.java
Labels: test

#156 [feat] : 결제 기능 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/common/exception/PayCardErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/common/exception/PayCardException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/common/exception/PointTransactionErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/common/exception/PointTransactionException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PayCard.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PointAwardReasonMessage.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PointRewardRatio.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/domain/PointTransaction.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/repository/PayCardRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/repository/PointTransactionRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/service/PayCardService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/service/PointTransactionService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/payment/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/payment/common/exception/PaymentErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/payment/common/exception/PaymentException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/payment/domain/Payment.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/payment/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/payment/repository/PaymentRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/payment/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/payment/service/PaymentService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderCreateTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/domain/PayCardTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/domain/PointRewardRatioTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/service/PayCardServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/service/PointTransactionServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/payment/service/PaymentServiceTest.java
Labels: feature

#187 [test] 회원가입 입력값 검증 로직 테스트 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/validation/validator/ValidPasswordValidator.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/service/MemberServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/validation/validator/ValidEmailValidatorTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/validation/validator/ValidNameValidatorTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/validation/validator/ValidNicknameValidatorTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/validation/validator/ValidPasswordValidatorTest.java
Labels: test

#197 [test] 액세스 토큰 재발급 테스트 코드 작성
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/service/AuthServiceTest.java
Labels: test

#179 [feat] 매장 주문 목록 조회 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/success/OrderSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/주문API.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/StoreOrderItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/StoreOrderResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/repository/OrderRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: feature

#183 [feat] 매장 주문 상세 조회 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/exception/OrderErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/success/OrderSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/StoreOrderDetailResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: feature

#204 [refactor] 병합 후 생긴 코드 수정
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/success/OrderSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: refactor

#190 [feat] 음료 상세 조회 기능
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/common/success/ItemSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/ItemController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/item-api-test.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/dto/common/ImageUrl.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/dto/response/ItemDetailResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/repository/BeverageItemRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/service/ItemService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/item/service/ItemServiceTest.java
Labels: feature

#192 [feat] 디저트 상세 조회 기능
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/common/success/ItemSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/ItemController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/controller/item-api-test.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/dto/common/ImageUrl.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/dto/response/ItemDetailResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/item/service/ItemService.java
Labels: feature

#200 [feat] 회원 가입시 PayCard 생성 로직 추가
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/event/MemberSignedUpEvent.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/service/MemberService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/common/exception/PayCardErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/eventlistener/MemberSignupEventListener.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/repository/PayCardRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/service/PayCardService.java
  starbucks/src/main/resources/application.yml
  starbucks/src/test/java/git_kkalnane/backend/starbucks/paycard/service/PayCardServiceTest.java
Labels: feature

#206 [test] 멤버 상세 정보 조회, 닉네임 변경, 비밀번호 변경 로직 테스트 구현
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/service/MemberServiceTest.java
Labels: test

#205 [feat] 사용자 상세정보 조회, 사용자 닉네임 갱신, 사용자 비밀번호 갱신 로직 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/common/success/MemberSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/controller/MemberController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/domain/Member.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/dto/request/SignUpRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/dto/request/UpdateNicknameRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/dto/request/UpdatePasswordRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/dto/response/MemberDetailInfo.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/service/MemberService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/service/MemberServiceTest.java
Labels: feature

#202 [feat] 주문이 수행될 때(결제가 이루어질 경우) PayCard 금액이 차감되는 로직 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/주문API.http
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
Labels: feature

#211 [feat] 매장 주문 상태 변경 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/exception/OrderErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/success/OrderSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/domain/Order.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/domain/OrderStatus.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/request/StoreOrderStatusUpdateRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: feature

#217 [feat] 매장 회원가입 기능 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/config/WebConfig.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/validation/annotation/ValidEmail.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/validation/annotation/ValidName.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/validation/annotation/ValidNickname.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/validation/annotation/ValidPassword.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/validation/validator/ValidEmailValidator.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/validation/validator/ValidNameValidator.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/validation/validator/ValidNicknameValidator.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/validation/validator/ValidPasswordValidator.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/dto/request/SignUpRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/dto/request/UpdateNicknameRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/member/dto/request/UpdatePasswordRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/common/exception/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/common/exception/MerchantErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/common/exception/MerchantException.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/common/success/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/common/success/MerchantSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/controller/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/controller/MerchantController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/domain/Merchant.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/dto/request/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/dto/request/SignUpRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/repository/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/repository/MerchantRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/service/.gitkeep
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/service/MerchantService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/_global/validation/validator/ValidEmailValidatorTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/_global/validation/validator/ValidNameValidatorTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/_global/validation/validator/ValidNicknameValidatorTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/_global/validation/validator/ValidPasswordValidatorTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/member/service/MemberServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/merchant/service/MerchantServiceTest.java
Labels: feature

#218 [feat] 매장 과거 주문 목록 조회 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/common/success/OrderSuccessCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/controller/OrderController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/StoreOrderHistoryListResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/dto/response/StoreOrderHistoryResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/repository/OrderRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/order/service/OrderService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/order/OrderServiceTest.java
Labels: feature

#216 [test] 메뉴 조회 로직 테스트코드 작성
  starbucks/src/test/java/git_kkalnane/backend/starbucks/cart/CheckCartItemTest.java
Labels: test

#208 [refactor] 알림 전송 이벤트 및 AOP 구현 리팩토링
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/aop/NotificationAspect.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/NotificationController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/Notification.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/NotificationType.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/request/OrderNotificationSendRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/OrderNotificationSendBeverageItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/OrderNotificationSendDessertItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/OrderNotificationSendResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/event/NotificationEventListener.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/event/OrderNotificationSendEvent.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/service/NotificationService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/NotificationServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/aop/NotificationAspectUnitTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/event/NotificationEventListenerTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/event/NotificationEventPublisherTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/event/OrderNotificationSendEventTest.java
Labels: refactor

#207 [feat] 알림 전송 기능 이벤트 및 AOP 개발
  starbucks/src/main/java/git_kkalnane/backend/starbucks/StarbucksApplication.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/aop/NotificationAspect.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/controller/NotificationController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/Notification.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/NotificationTargetType.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/NotificationType.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/domain/OrderNotification.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/request/OrderNotificationSendRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/NotificationItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/OrderNotificationSendBeverageItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/OrderNotificationSendDessertItemResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/dto/response/OrderNotificationSendResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/event/NotificationEventListener.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/event/NotificationEventPublisher.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/event/OrderNotificationSendEvent.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/repository/OrderNotificationRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/notification/service/NotificationService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/NotificationServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/aop/NotificationAspectUnitTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/event/NotificationEventListenerTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/event/NotificationEventPublisherTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/notification/event/OrderNotificationSendEventTest.java
Labels: feature

#228 fix: ModifyCartItemResponse()
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/controller/CartController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/service/CartService.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/cart/CartModifyTest.java
Labels: fix

#231 [Feat] 카트 생성 로직 추가
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/common/exception/CartErrorCode.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/repository/CartRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/cart/service/CartService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/domain/Merchant.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/paycard/eventlistener/MemberSignupEventListener.java
Labels: feature

#230 [feat] Merchant(매장) 로그인 구현
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/config/MemberAuthInterceptor.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/config/MerchantAuthInterceptor.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/_global/config/WebConfig.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/dto/request/LoginRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtTokenProvider.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/LoginDto.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/request/LoginRequest.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/dto/response/LoginResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/member/controller/MemberAuthController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/member/domain/MemberRefreshToken.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/member/dto/MemberLoginDto.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/member/dto/response/MemberLoginResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/member/repository/MemberRefreshTokenRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/member/service/MemberAuthService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/merchant/controller/MerchantAuthController.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/merchant/domain/MerchantRefreshToken.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/merchant/dto/MerchantLoginDto.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/merchant/dto/response/MerchantLoginResponse.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/merchant/repository/MerchantRefreshTokenRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/merchant/service/MerchantAuthService.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/auth/repository/RefreshTokenRepository.java
  starbucks/src/main/java/git_kkalnane/backend/starbucks/merchant/controller/MerchantController.java
  starbucks/src/main/resources/application.yml
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/common/jwt/JwtTokenProviderTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/member/service/MemberAuthServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/merchant/service/MerchantAuthServiceTest.java
  starbucks/src/test/java/git_kkalnane/backend/starbucks/auth/service/AuthServiceTest.java
Labels: feature
